/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.HeadlessException;
/**
 *
 * @author ADHITYAAP
 */import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class pendataan extends javax.swing.JFrame {
DefaultTableModel tabModel;
ResultSet RsProduk=null;
    /**
     * Creates new form pendataan
     */
    public pendataan() {
        initComponents();
        setLocationRelativeTo(this);
        load_table();
        kosong();
    }
    private void load_table(){
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Umur");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Kondisi");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            String sql = "select * from data";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            jTableProduk.setModel(model);
        } catch (Exception e) {
        }}
    
private void cariData(String key){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
         model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Umur");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Alamat");
        model.addColumn("Kondisi");
        
        //menampilkan data database kedalam tabel
        try {
            int no=1;
            
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery("SELECT * from data WHERE nik LIKE '%"+key+"%' OR nama LIKE '%"+key+"%' OR jk LIKE '%"+key+"%'");
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6)});
            }
            jTableProduk.setModel(model);
        } catch (Exception e) {
        }
    }
private void kosong(){
        txt_alamat.setText(null);
        txt_nik.setText(null);
        txt_kondisi.setText(null);
        txt_umur.setText(null); 
        txt_nama.setText(null);  
        txt_jk.setSelectedItem(this);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_nik = new javax.swing.JTextField();
        txt_umur = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_jk = new javax.swing.JComboBox<>();
        btn_simpan = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txt_kondisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduk = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_nama = new javax.swing.JTextField();
        jTextPencarian = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Kejadian = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txt_nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 193, -1));
        getContentPane().add(txt_umur, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 193, -1));
        getContentPane().add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 193, -1));

        txt_jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Jenis Kelamin---", "Laki-Laki", "Perempuan", " " }));
        getContentPane().add(txt_jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        btn_simpan.setText("SIMPAN");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, -1, -1));
        getContentPane().add(txt_kondisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 193, -1));

        jTableProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIK", "Nama ", "Umur", "Jenis Kelamin", "Alamat", "Kondisi"
            }
        ));
        jTableProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 440, 275));

        jButton1.setText("HAPUS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 530, -1, -1));

        jButton4.setText("CLEAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, -1, -1));
        getContentPane().add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 193, -1));

        jTextPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextPencarianKeyReleased(evt);
            }
        });
        getContentPane().add(jTextPencarian, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 230, -1));

        jButton3.setText("CARI");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        jButton5.setText("EXIT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, -1, -1));

        Kejadian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                KejadianPropertyChange(evt);
            }
        });
        getContentPane().add(Kejadian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 190, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/a (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
      
     try {  
            String sql = "INSERT INTO data VALUES ('"+txt_nik.getText()+"','"+txt_nama.getText()+"','"+txt_umur.getText()+"','"+txt_jk.getSelectedItem()+"','"+txt_alamat.getText()+"','"+txt_kondisi.getText()+"')";
           java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            
            pst.execute();
            
             new pendataan().setVisible(true);
             dispose();
            JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }   
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void jTableProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProdukMouseClicked
        // TODO add your handling code here:
         int baris = jTableProduk.rowAtPoint(evt.getPoint());
         
        String nik =jTableProduk.getValueAt(baris, 1).toString();
        txt_nik.setText(nik);
        String nama =jTableProduk.getValueAt(baris, 2).toString();
        txt_nama.setText(nama);
        String umur = jTableProduk.getValueAt(baris,3).toString();
        txt_umur.setText(umur);
        String jk = jTableProduk.getValueAt(baris, 4).toString();
        txt_jk.setSelectedItem(jk);
        String alamat=jTableProduk.getValueAt(baris, 5).toString();
        txt_alamat.setText(alamat);
        String kondisi = jTableProduk.getValueAt(baris, 6).toString();
        txt_kondisi.setText(kondisi);
    }//GEN-LAST:event_jTableProdukMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
            String sql ="UPDATE data SET nik = '"+txt_nik.getText()+"',nama = '"+txt_nama.getText()+"',umur = '"+txt_umur.getText()+"',jk = '"+txt_jk.getSelectedItem()+"',alamat= '"+txt_alamat.getText()+"',kondisi= '"+txt_kondisi.getText()+"' WHERE nik = '"+txt_nik.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="delete from data where nik='"+txt_nik.getText()+"'";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(this, "berhasil di hapus");
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPencarianKeyReleased
        // TODO add your handling code here:
        String key=jTextPencarian.getText();
        System.out.println(key);  
        
        if(key!=""){
            cariData(key);
        }else{
            load_table();
        }
    }//GEN-LAST:event_jTextPencarianKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
           dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void KejadianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_KejadianPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_KejadianPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pendataan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pendataan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Kejadian;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProduk;
    private javax.swing.JTextField jTextPencarian;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JComboBox<String> txt_jk;
    private javax.swing.JTextField txt_kondisi;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nik;
    private javax.swing.JTextField txt_umur;
    // End of variables declaration//GEN-END:variables
}
